version: '3.8'

services:
  autoservice-app:
    build: .
    container_name: autoservice-app
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-Xmx512m
    restart: unless-stopped